/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CustomerOrganization;
import Business.Organization.EventManagementOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;

/**
 *
 * @author THISPC
 */
public class CustomerRequestJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;

    /**
     * Creates new form CustomerRequestJPanel
     */
    public CustomerRequestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (CustomerOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hallTypeTxt = new javax.swing.JTextField();
        foodTypeTxt = new javax.swing.JTextField();
        hallPriceTxt = new javax.swing.JTextField();
        foodPriceTxt = new javax.swing.JTextField();
        quantityTxt = new javax.swing.JTextField();
        request2Btn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("HallType");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jLabel2.setText("FoodType");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 118, -1, -1));

        jLabel3.setText("HallPrice");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, 20));

        jLabel4.setText("FoodPrice");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel5.setText("Quantity");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));
        add(hallTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 71, 91, -1));
        add(foodTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 115, 91, -1));
        add(hallPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 159, 91, -1));
        add(foodPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 203, 91, -1));
        add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 247, 91, -1));

        request2Btn.setBackground(new java.awt.Color(0, 102, 255));
        request2Btn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        request2Btn.setForeground(new java.awt.Color(255, 255, 255));
        request2Btn.setText("Request");
        request2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                request2BtnActionPerformed(evt);
            }
        });
        add(request2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 102, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 364, -1, -1));

        jLabel6.setText("Date");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 294, -1, -1));
        add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void request2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_request2BtnActionPerformed

        if( hallTypeTxt.getText().isEmpty() || foodTypeTxt.getText().isEmpty() || foodTypeTxt.getText().isEmpty() || hallPriceTxt.getText().isEmpty() || foodPriceTxt.getText().isEmpty() || quantityTxt.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Fields Cannot be Empty");
        }

        try{
            Integer.parseInt(hallPriceTxt.getText() );
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "HallPrice should be numbers");
            return;
        }
        
        try{
            Integer.parseInt(foodPriceTxt.getText() );
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "FoodPrice should be numbers");
            return;
        }
        

        try{
            Integer.parseInt(quantityTxt.getText() );
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Quantity should be numbers");
            return;
        }

        // TODO add your handling code here:
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
          String message = quantityTxt.getText();
          String hall = hallTypeTxt.getText();
          String food = foodTypeTxt.getText();
          String hallPrice = hallPriceTxt.getText();
          String foodPrice = foodPriceTxt.getText();
          //String date = dateTF.getText();
          Date date = jXDatePicker1.getDate();
        Date currentDate = new Date();
if (date.before(currentDate)) {
 
    JOptionPane.showMessageDialog(null,"ERROR! CANNOT BOOK FOR PREVIOUS DATES");
}
        
        LabTestWorkRequest request1 = new LabTestWorkRequest();
        WorkRequest wr1 = new WorkRequest() {};
       request1.setMessage(message);
        request1.setSender(account);
        request1.setStatus("Sent");
        request1.setHallType(hall);
        request1.setFoodType(food);
        request1.setHallPrice(hallPrice);
        request1.setFoodPrice(foodPrice);
        //request1.setDate(date);
        String strDate = dFormat.format(date);
        request1.setDate(strDate);
      
       //  wr1.setHallType(hallTypeTxt.getText());
        //wr1.setFoodType(foodTypeTxt.getText());
       // wr1.setHallPrice(hallPriceTxt.getText());
      //  wr1.setFoodPrice(foodPriceTxt.getText());
      //  wr1.setQuantity(quantityTxt.getText());
        
            Organization org = null;
           for(Network network : business.getNetworkList()){
           for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){    
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof EventManagementOrganization){
                org = organization;
                break;
            }
        }
           }
           }
           
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request1);
            account.getWorkQueue().getWorkRequestList().add(request1);
        }
  
        JOptionPane.showMessageDialog(null, "Request created successfully");
        
        foodTypeTxt.setText("");
        hallTypeTxt.setText("");
        foodPriceTxt.setText("");
        hallPriceTxt.setText("");
        quantityTxt.setText("");
        //dateTF.setText("");
        //jXDatePicker1.setValue("");
        

         

    }//GEN-LAST:event_request2BtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray1 = userProcessContainer.getComponents();
        Component component = componentArray1[componentArray1.length - 1];
        CustomerDetails cd = (CustomerDetails) component;
        cd.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField foodPriceTxt;
    private javax.swing.JTextField foodTypeTxt;
    private javax.swing.JTextField hallPriceTxt;
    private javax.swing.JTextField hallTypeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton request2Btn;
    // End of variables declaration//GEN-END:variables
}
