/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.EMEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Caterer;
import Business.Organization.CatererOrganization;
import Business.Organization.CustomerOrganization;
import Business.Organization.EventManagementOrganization;
import Business.Organization.Organization;
import Business.Organization.PartyHall;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shephali Mahajan
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (CustomerOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
        
        populateTable();
        populateCatererTable();
    }
    
    public void populateTable(){
               DefaultTableModel model = (DefaultTableModel) tblHall1.getModel();
        
        model.setRowCount(0);
        for(Network n : business.getNetworkList())
        {
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof EMEnterprise){
                        for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                            if(o instanceof EventManagementOrganization){
                                for(PartyHall p : ((EventManagementOrganization)o).getPartyHallDirectory().getPartyHallDirectory()){
                                    Object[] row = new Object[6];
                                    row[0] = p.getName();
                                    row[1] = p.getHallType();
                                    row[2] = p.getPrice();
                        
                                    model.addRow(row);
                                }
                            }
                        }
                }
            }
        }
    
        
            
          
        
    }
    
    public void populateCatererTable(){
             DefaultTableModel model = (DefaultTableModel) catererJTable.getModel();
        
        model.setRowCount(0);
        for(Network n : business.getNetworkList())
        {
            for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof EMEnterprise){
                        for(Organization o : e.getOrganizationDirectory().getOrganizationList()){
                            if(o instanceof CatererOrganization){
                                for(Caterer c : ((CatererOrganization)o).getCatererDirectory().getCatererDirectory()){
                                    Object[] row = new Object[6];
                                    row[0] = c.getName();
                                    row[1] = c.getCuisineType();
                                    row[2] = c.getPrice();
                        
                                    model.addRow(row);
                                }
                            }
                        }
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHall1 = new javax.swing.JTable();
        bookEMBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        catererJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHall1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hall Type", "Name", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblHall1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 320, 140));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 67, 390, 260));

        bookEMBtn.setBackground(new java.awt.Color(0, 102, 255));
        bookEMBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bookEMBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookEMBtn.setText("Book Event Manager");
        bookEMBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookEMBtnActionPerformed(evt);
            }
        });
        add(bookEMBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 240, -1));

        catererJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CuisineType", "Name", "Price"
            }
        ));
        jScrollPane1.setViewportView(catererJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 89, 340, 133));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Hall List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FoodType List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bookEMBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookEMBtnActionPerformed

           // TODO add your handling code here:
          CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CustomerDetails", new CustomerDetails(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_bookEMBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookEMBtn;
    private javax.swing.JTable catererJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHall1;
    // End of variables declaration//GEN-END:variables
}
