/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CatererRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CatererOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.EventManagerRole.ManagePartyHallJPanel;

/**
 *
 * @author THISPC
 */
public class CatererWorkAreaJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    /**
     * Creates new form CatererMainJPanel
     */
    public CatererWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (CatererOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageCatererBtn = new javax.swing.JButton();
        processRequestBtn = new javax.swing.JButton();
        ManageWsteFoodBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Caterer Work Area Panel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 47, -1, -1));

        manageCatererBtn.setBackground(new java.awt.Color(0, 102, 255));
        manageCatererBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageCatererBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageCatererBtn.setText("Manage Caterers");
        manageCatererBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCatererBtnActionPerformed(evt);
            }
        });
        add(manageCatererBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 145, 200, -1));

        processRequestBtn.setText("Process Request");
        processRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processRequestBtnActionPerformed(evt);
            }
        });
        add(processRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 190, -1));

        ManageWsteFoodBtn.setText("Manage Left Food");
        ManageWsteFoodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageWsteFoodBtnActionPerformed(evt);
            }
        });
        add(ManageWsteFoodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 197, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageCatererBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCatererBtnActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageCaterersJPanel", new ManageCaterersJPanel(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer);  
    }//GEN-LAST:event_manageCatererBtnActionPerformed

    private void processRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processRequestBtnActionPerformed
        // TODO add your handling code here:
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CatererRequestJPanel", new CatererRequestJPanel(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer);
        
       
    }//GEN-LAST:event_processRequestBtnActionPerformed

    private void ManageWsteFoodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageWsteFoodBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CatererManageWasteFoodTable", new CatererManageWasteFoodTable(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageWsteFoodBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageWsteFoodBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCatererBtn;
    private javax.swing.JButton processRequestBtn;
    // End of variables declaration//GEN-END:variables
}
