/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CatererRole;import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Caterer;
import Business.Organization.CatererDirectory;
import Business.Organization.CatererOrganization;
import Business.Organization.EventManagementOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.Caterer;
import Business.Organization.PartyHall;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author chano
 */
public class CatererManageWasteFoodRequest extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    /**
     * Creates new form CatererManageWasteFood
     */
    public CatererManageWasteFoodRequest(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (CatererOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FoodTypeTF = new javax.swing.JTextField();
        QuantityLeftTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Waste Food");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 51, -1, -1));

        jLabel2.setText("Food Type");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 114, -1, -1));

        jLabel3.setText("Quantity Left");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 211, 118, -1));
        add(FoodTypeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 108, 151, -1));
        add(QuantityLeftTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 205, 151, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Notify Event Manager");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if( QuantityLeftTF.getText().isEmpty() || FoodTypeTF.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Fields Cannot be Empty");
        }

        try{
            Integer.parseInt(QuantityLeftTF.getText());
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Price should be numbers");
            return;
        }

        
        String quantityLeft = QuantityLeftTF.getText();
        String foodLeftType = FoodTypeTF.getText();
        
        LabTestWorkRequest request = new LabTestWorkRequest();
        WorkRequest wr = new WorkRequest() {};
        request.setLeftFoodQuantity(quantityLeft);
        request.setLeftFoodType(foodLeftType);
        request.setSender(account);
        request.setStatus("Sent");
        wr.setLeftFoodQuantity(QuantityLeftTF.getText());
        wr.setLeftFoodType(FoodTypeTF.getText());
        //wr.setDate(DateTF.getText());
        //wr.setQuantity(QuantityTF.getText());
        
        
        
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof EventManagementOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            account.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(null, "Event Manager Notified");
        QuantityLeftTF.setText("");
        FoodTypeTF.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CatererManageWasteFoodTable dwjp = (CatererManageWasteFoodTable) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FoodTypeTF;
    private javax.swing.JTextField QuantityLeftTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
