/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EventManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EventManagementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.DoctorRole.DoctorWorkAreaJPanel;
import userinterface.DoctorRole.RequestLabTestJPanel;

/**
 *
 * @author Shephali Mahajan
 */
public class EventManagerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private EventManagementOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    /**
     * Creates new form EventManagerWorkAreaJPanel
     */
    public EventManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EventManagementOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManagePartyHalls = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        manageCustomerBtn = new javax.swing.JButton();
        manageNGOBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Event Manager Work Area JPanel");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 1080, -1));

        btnManagePartyHalls.setBackground(new java.awt.Color(0, 102, 255));
        btnManagePartyHalls.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnManagePartyHalls.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePartyHalls.setText("Manage Party Halls");
        btnManagePartyHalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePartyHallsActionPerformed(evt);
            }
        });
        add(btnManagePartyHalls, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 151, 326, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Request Caterer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 212, 326, -1));

        manageCustomerBtn.setBackground(new java.awt.Color(0, 102, 255));
        manageCustomerBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageCustomerBtn.setText("Manage Customer Requests");
        manageCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerBtnActionPerformed(evt);
            }
        });
        add(manageCustomerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 279, 326, -1));

        manageNGOBtn.setBackground(new java.awt.Color(0, 102, 255));
        manageNGOBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        manageNGOBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageNGOBtn.setText("Manage Left Food");
        manageNGOBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNGOBtnActionPerformed(evt);
            }
        });
        add(manageNGOBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 344, 326, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Request From Caterer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 330, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("DoctorWorkAreaJPanel", new DoctorWorkAreaJPanel(userProcessContainer, account,(EventManagementOrganization) organization,enterprise));
        layout.next(userProcessContainer);  
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnManagePartyHallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePartyHallsActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManagePartyHallJPanel", new ManagePartyHallJPanel(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagePartyHallsActionPerformed

    private void manageCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageCustomerRequestJPanel", new ManageCustomerRequestJPanel(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_manageCustomerBtnActionPerformed

    private void manageNGOBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNGOBtnActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ManageNGORequestJPanel", new ManageNGORequestJPanel(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer); 
        
    }//GEN-LAST:event_manageNGOBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("WasteFoodRequestJPanel", new WasteFoodRequestJPanel(userProcessContainer, account, organization,enterprise,business));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagePartyHalls;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCustomerBtn;
    private javax.swing.JButton manageNGOBtn;
    // End of variables declaration//GEN-END:variables
}
