/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EventManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.EventManagementOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CustomerRole.CustomerDetails;

/**
 *
 * @author THISPC
 */
public class ManageNGOProcessRequestJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private EventManagementOrganization organization;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;


    /**
     * Creates new form ManageNGOProcessRequestJPanel
     */
    public ManageNGOProcessRequestJPanel(JPanel userProcessContainer, UserAccount account, EventManagementOrganization emOrganization, Enterprise enterprise, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = emOrganization;
        this.enterprise = enterprise;
        this.business = business;
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Quantity");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 84, -1, -1));
        add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 81, 112, -1));

        submitBtn.setBackground(new java.awt.Color(0, 102, 255));
        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 149, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 102, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if( quantityTxt.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Fields Cannot be Empty");
        }
        else 
        {
         try{
            Integer.parseInt(quantityTxt.getText());
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Price should be numbers and Cannot be blank");
            return;
        }


        String message = quantityTxt.getText();
        
           LabTestWorkRequest request1 = new LabTestWorkRequest();
        //WorkRequest wr1 = new WorkRequest() {};
      
        request1.setSender(account);
        request1.setStatus("Sent");
        request1.setQuantity(quantityTxt.getText());
        // request1.setQuantity(message);
        
            Organization org = null;
           for(Network network : business.getNetworkList()){
           for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){    
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NGOOrganization){
                org = organization;
                break;
            }
        }
        }
           }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request1);
            account.getWorkQueue().getWorkRequestList().add(request1);
        }
  
             JOptionPane.showMessageDialog(null, "Request created Succesfully");   
             quantityTxt.setText("");
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         Component[] componentArray2 = userProcessContainer.getComponents();
        Component component2 = componentArray2[componentArray2.length - 1];
        ManageNGORequestJPanel mnr = (ManageNGORequestJPanel) component2;
        mnr.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
