/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NGO;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.EventManagerRole.ManageCustomerProcessRequest;
import userinterface.EventManagerRole.ManageNGORequestJPanel;

/**
 *
 * @author THISPC
 */
public class ManageRequestJPanel extends javax.swing.JPanel {
        private JPanel userProcessContainer;
    private UserAccount account;
    private NGOOrganization NGOOrganization;
    private Enterprise enterprise;
    private EcoSystem business;

    /**
     * Creates new form ManageRequestJPanel
     */
    public ManageRequestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.NGOOrganization = (NGOOrganization)organization;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
       
    }
    
       public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)manageNGOTbl.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request :NGOOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[6];
           row[0] = request;
          // row[1] = request.getReceiver();
           row[3] = request.getQuantity();
           row[4] = request.getStatus();
            
           
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            
        
            
            
            model.addRow(row);
        }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manageNGOTbl = new javax.swing.JTable();
        assignBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageNGOTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "Sender", "Receiver", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(manageNGOTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 85, 410, 150));

        assignBtn.setBackground(new java.awt.Color(0, 102, 255));
        assignBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        assignBtn.setForeground(new java.awt.Color(255, 255, 255));
        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 304, -1, -1));

        processBtn.setBackground(new java.awt.Color(0, 102, 255));
        processBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        processBtn.setForeground(new java.awt.Color(255, 255, 255));
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        backBtn.setBackground(new java.awt.Color(0, 102, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 304, -1, -1));

        refreshBtn.setBackground(new java.awt.Color(0, 102, 255));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 26, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = manageNGOTbl.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        LabTestWorkRequest request = (LabTestWorkRequest)manageNGOTbl.getValueAt(selectedRow, 0);
     
        request.setStatus("Processing");
        
        ManageNGOProcessJPanel manageNGOProcessJPanel = new ManageNGOProcessJPanel(userProcessContainer, request);
        userProcessContainer.add("ManageNGOProcessJPanel", manageNGOProcessJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = manageNGOTbl.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        WorkRequest request1 = (WorkRequest)manageNGOTbl.getValueAt(selectedRow, 0);
        request1.setReceiver(account);
        request1.setStatus("Pending");
        populateTable();
        JOptionPane.showMessageDialog(null, "Request assigned to you");
    }//GEN-LAST:event_assignBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
         
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageNGOTbl;
    private javax.swing.JButton processBtn;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
